// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription

let package = Package(
    name: "Diffusion",
    platforms: [
        .iOS("16.2")
    ],
    products: [],
    dependencies: [
        	.package(url: "https://github.com/apple/ml-stable-diffusion", branch: "main"),
		.package(url: "https://github.com/mxcl/Path.swift.git", "1.0.0"..<"2.0.0"),
		.package(url: "https://github.com/weichsel/ZIPFoundation.git", "0.9.9"..<"1.0.0"),
		.package(url: "https://github.com/buh/CompactSlider.git", branch: "main"),
    ],
    targets: [
        .executableTarget(
            name: "Diffusion",
            dependencies: [
                .product(name: "StableDiffusion", package: "ml-stable-diffusion"),
                .product(name: "Path", package: "Path.swift"),
                .product(name: "ZIPFoundation", package: "ZIPFoundation"),
                .product(name: "CompactSlider", package: "CompactSlider"),
            ],
            path: "Diffusion"
        ),
        .testTarget(
            name: "DiffusionTests",
            dependencies: [
                "Diffusion"
            ],
            path: "DiffusionTests"
        ),
    ]
)

#if canImport(AppleProductTypes)
    import AppleProductTypes

    package.products += [
        .iOSApplication(
            name: "Diffusion",
            targets: ["Diffusion"],
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone,
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad])),
            ],
            additionalInfoPlistContentFilePath: "Diffusion/Info.plist"
        )
    ]
#endif
